version: '3.8'

services:
  main:
    container_name: main
    build: 
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
      - "9229:9229"
    command: npm run dev
    depends_on:
      - postgres
    restart: always
  
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: nest-course
      POSTGRES_USER: asan
      POSTGRES_PASSWORD: asan_0707
    entrypoint: "/bin/sh -c 'mkdir -p /var/lib/postgresql/data && chown -R postgres:postgres /var/lib/postgresql/data && exec docker-entrypoint.sh '"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
